#define PUSH(arg) StackPush(spu->stk, arg)
#define POP       StackPop(spu->stk)

DEF_COM (push, 1,  1)
DEF_COM (pop,  2,  1)
DEF_COM (in,   3,  0)
DEF_COM (out,  4,  0)
DEF_COM (add,  5,  0)
DEF_COM (sub,  6,  0)
DEF_COM (mul,  7,  0)
DEF_COM (div,  8,  0)
DEF_COM (mod,  9,  0)
DEF_COM (abs,  10, 0)
DEF_COM (sin,  11, 0)
DEF_COM (cos,  12, 0)
DEF_COM (sqrt, 13, 0)
DEF_COM (hlt,  -1, 0)
